projectName: teste2
namespace: default

serviceAccount:
  enabled: false
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/teste2-production

deployment:
  datadog:
      enabled: true
      env: "production"
  # initContainers:
  # - name: exemplo
  #   image: busy:box
  #   command: ["echo", "Hello, Kubernetes!"]
  # command: []
  labels: {}
  annotations: {}
  # targetContainer: "teste2" # Nome do contêiner para o qual o service deve apontar
  containers:
    - name: teste2
      image:
        registry: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
        repository: "teste2"
        tag: dfc9fd1
      readinessProbe:
        # tcpSocket:
        #   port: 3000
        # exec:
        #   command: ["echo", "Hello, Kubernetes!"]
        healthPath: /health
        failureThreshold: 3
        initialDelaySeconds: 150
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      livenessProbe:
        # tcpSocket:
        #   port: 3000
        # exec:
        #   command: ["echo", "Hello, Kubernetes!"]
        healthPath: /health
        failureThreshold: 3
        initialDelaySeconds: 150
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 10
      port: 3000
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: teste2-config
        - secretRef:
            name: teste2-secret
      env: {}
      volumeMounts: {}
      #   - name: volume-name
      #     mountPath: "/path/to/mount"
      #     readOnly: true
      lifecycle: {}
        # postStart:
        #   exec:
        #     command: ["/bin/sh", "-c", "cp -r /app/. /var/www/app"]
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes: []
  # - name: volume-name
  #   emptyDir: {}

configMaps:
  - name: teste2-config
    data:
      ENVIRONMENT: "production"


secrets: {}

externalSecrets: 
  - name: teste2-secret
    refreshInterval: 5m
    useProperty: true
    data:


hpa: 
  minReplicas: 1
  maxReplicas: 10
  cpuAverage: 160
  memoryAverage: 160

ingress:
- name: public
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: default-public
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789012:certificate/default
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: chatbot.com.br
      paths:
        - path: /
          portNumber: 3000
          pathType: Prefix